In [4]:
import numpy as np
import matplotlib.pyplot as plt
import math
import vpython as vp
import scipy

%matplotlib inline

### Uso do if 
Para impor uma condição usamos *if + condição*

In [2]:
#Exemplo para ver se um número é maior, próximo
# ou menor que 10

if x>10:
    print("Número maior que 10")
elif x>9:
    print("O número é Ok, mas estás muito perto")
else:
    print("O número é bom, ou seja, é menor que 10")

NameError: name 'x' is not defined

### Uso do while
Para realizar um determinado número de iterações dependentes de uma condição usamos o *while + condição*

In [ ]:
#Exemplo colocamos um número maior que 10 é nos
#pedido para inserir um novo número até que
#coloquemos um número menor que 10

x=int(input("Número escolhido: "))
while x>10:
    x=int(input("Escolha outro número: "))
print("Certo! ", x," < 10")

### Uso do break
Podemos impor uma condição para que o programa saia do *loop while* independentemente se a condição do loop não foi ainda cumprida para que este acabe

In [ ]:
x=int(input("Número escolhido: "))
while x>10:
    if x==11:
        break
    x=int(input("Escolha outro número: "))
print("Certo! ", x," < 10")

Ex: Catalan numbers - page 46

In [ ]:
c0 = 1
cn1 = 1
n=0
x=int(input("Number of catalan numbers: "))
print("Catalan numbers till ", x)
while n!=x:
    cn = (4*n+2)/(n+2)*cn1
    cn1 = cn
    n+=1
    print(int(cn))

### Listas de elementos
Escrevemos listas de elementos da seguinte forma:

In [ ]:
list = [1,2,3,4,5,6]
print(list)

x=1
y=2
list2 = [x,y]
print(list2)

#mudemos o valor de x, mas dentro da lista2 
#o valor permanecerá o mesmo

x=3
print(list2)

#Imprimir apenas o 1º elemento da list

print(list[0])

#Atribuir novos valores a elementos da lsita

list[2] = 100
print(list)

#Função python para somar elementos de uma lista

soma = sum(list)
print(soma)

#Função python para saber o tamanho de uma lista

tamanho = len(list)
print(tamanho)

#Para adicionar elementos a uma lista usamos a função append

l.append(7.2)
print(l)

#Para remover elementos usamos a função pop
#identificando a posição do elemento que queremos retirar

l.pop(3)
print(l)



In [ ]:
#Fazer operações a uma lista de elementos dando origem
# a uma nova lsita com os resultados dessas operações

from math import log
l=[1.0,1.5,2.0]
listlog = list(map(log,l))
print(list_log)


### Arrays

###### Diferenças entre lists e arrays:
-> o número de elementos é fixo, ou seja, o array é imutável não podendo ser adicionados ou removidos elementos;
-> os elementos de um array só podem ser de um único tipo (int, string, float,...).

###### Vantagens dos arrays:
-> podemos utilizar para criar matrizes, visto que os arrays podem ter multiplas dimensões;
-> comportam-se como vetores ou matrizes, podendo somar-se arrays entre si (vetores/matrizes entre si);
-> funcionam mais rápidamente que as listas.


In [ ]:
#Criar vetores nulos

from numpy import zeros
vec = zeros(3, float)
print(vec)

#Criar matrizes nulas

mat = zeros([4,4], float)
print("\n", mat, "\n")

#Converter listas em arrays

from numpy import array

list = [1,2,3,4]
arr = array(list,int)
print(arr, "\n")

#Array de 2 dimensões

arr = array([[1,2,3],[4,5,6]],int)
print (arr, "\n")

#Criar matrizes

from numpy import zeros
arr = zeros([2,2],int)
arr[0,1]=1                   # 1ª linha e 2ª coluna
arr[1,0]=-1                  # 2ª linha e 1ª coluna
print(arr, "\n")



### Ler arrays de um file
Podemos criar um array a partir um conjunto de valores de um ficheiro, através da função *loadtxt*. Exemplo se tivermos um ficheiro com os seguintes valores:
1
2
3
4
E o ficheiro tem o nome e values.txt, então:

In [ ]:
from numpy import loadtxt
arr = loadtxt("teste.txt", float)
print(arr, "\n")

arr2 = loadtxt("matrizteste2.txt", int)
print(arr2,"\n")

#Podemos fazer operações aritméticas em arrays

from numpy import array
a = array([1,2,3,4], int)
a2 = 2*a
print(a2, "\n")


b = array([0,1,2,3], int)
print(a+b, "\n")

#Multiplicação

print (a*b, "\n")

#Produto escalar entre vetores
print(np.dot(a,b),"\n")

#Produto matricial (entre matrizes)
mat1 = array([[1,2],[2,1]], int)
mat2 = array([[1,2],[2,1]], int)
print(np.dot(mat1,mat2))



In [ ]:
#Número de elementos de um vetor/matriz
print(mat1.size, "\n")

#Número de linhas e colunas respetivamente
print(mat1.shape, "\n")

#Copiar um array
mat3 = np.copy(mat1)
print(mat3, "\n")

#Dividir ou criar um novo array a partir de uma parte de outro array
a=[1,2,3,4,5,6,7,8,9]
b=a[2:5]        #inclui o elemento na posição 2, mas não o da posição 5
print(b,"\n")

### Loops for e ranges
Podemos usar o range para criar listas de valores, como por exemplo:

In [ ]:
#elementos de 0 a 5, sem incluir o 5
l=[]
for i in range(5):
     l.append(i)
print(l,"\n")

#elementos de 2 a 8, sem incluir o 8

l=[]
for i in range(2,8):
     l.append(i)
print(l, "\n")

#elementos de 2 em 2

l=[]
for i in range(0,10,2):
     l.append(i)
print(l)

### Importância do pacote  *pylab*

O pacote pylab é um pacote que contém funções aplicadas a análise e construção de gráficos de funções matemáticas

In [ ]:
#Exemplo de um gráfico

y=[1.0,2.4,1.7, 0.3, 0.6, 1.8]
plt.plot(y)
plt.show()

In [ ]:
#Criar um array contendo valores para aplicarmos a uma função

x=np.linspace(0,10,100)
y=np.sin(x)
plt.plot(x,y)
plt.show()

In [ ]:
#Podemos alterar a escala dos gráficos através das funções xlim e ylim

x=np.linspace(0,10,100)
y=np.sin(x)
plt.ylim(-2,2)

#Podemos alterar o design da curva
plt.plot(x,y,"ko") #podemos usar "ko", "g--", "k-", "k--"

#Podemos identificar os eixos através das seguintes funções

plt.xlabel("Eixo dos x")
plt.ylabel("Eixo dos y")

plt.show()


### *Scatter plots*
Gráficos de pontos, utilizado para representar por exemplo a relação entre a temperatura e o brilho de várias estrelas do universo:

In [ ]:
import numpy as np
data= np.loadtxt("stars.txt",float)
x = data[: ,0]
y = data [: ,1]
plt.scatter(x,y)
plt.xlabel("Temperatura")
plt.ylabel("Magnitude")
plt.xlim(0, 13000)
plt.ylim(-5,20)
plt.show()

### *Density plots*

Gráficos de densidade em 2 dimensões, por exemplo:

In [ ]:
data = np.loadtxt("circular.txt", float)
plt.imshow(data) 
plt.show()
#reparar que a origem está no topo do lado esquerdo

### Alterar cores dos gráficos
Pesquisar em matplotlib.org para acessar às diversas funções do pacote.

Cores disponíveis:

np.jet() - esquema de calor básico do mapa de calor

np.hot() - esquema alternativo para mapas de calor

np.bone()

np.hsv() - esquema de cores arco-íris


In [ ]:
data = np.loadtxt("circular.txt", float)
plt.imshow(data, origin = "lower") #a origem passa para o o canto esquerdo de baixo 
plt.gray() #torna o gráfico a preto e branco
plt.colorbar() #mostra o range de cores 
plt.show()

### Alterar formato do gráfico
Usamos a função $extent[x1,x2,y1,y2]$ para impor limites no eixo do $X$, indo do $x_1$ até ao $x_2$, e no eixo do $Y$, indo do $y_1 ao y_2$.

Usamos o aspect para alterar o formato da escala do gráfico

In [ ]:
data = np.loadtxt("circular.txt", float)
plt.imshow(data, origin = "lower", extent = [0,10,0,5], aspect = 0.5) 
plt.show()

### Pacote *vpython*
Pacote para formatar objetos ou animações em 3D

In [ ]:
import vpython as vp

scene = vp.canvas()
# Neste caso criámos uma esfera
s = vp.sphere(pos=vp.vector(0,0,0), radius=1, color=vp.color.green)

In [ ]:
scene = vp.canvas()
# Neste caso criámos uma esfera
s = vp.sphere(pos=vp.vector(0,0,0), radius=1, color=vp.color.orange)
s.color = vp.color.blue

In [ ]:
scene = vp.canvas()
# Neste caso criámos uma esfera
s = np.empty(10,vp.sphere)
for n in range(10):
    s[n]=vp.sphere()

In [ ]:
scene = vp.canvas()
# Neste caso criámos uma esfera
caixa = vp.box(pos=vp.vector(0, 0, 0), size=vp.vector(2, 1, 3), color=vp.color.blue)
seta = vp.arrow(pos=vp.vector(4, 4, 4), axis=vp.vector(-1, -1, -1), color=vp.color.red)


In [ ]:
#Mover uma esfera
scene = vp.canvas()

s = vp.sphere(pos=vp.vector(1,0,0), radius = 0.1)

for theta in np.linspace(0,10000000*np.pi,1000):
    vp.rate(30)
    x=np.cos(theta)
    y=np.sin(theta)
    s.pos=vp.vector(x,y,0)

### Erro numérico
Os números float apenas podem ser representados com 16 algarismos significativos de precisão

Além disso, ter cuidado com a igualdade entre floats 3.3 é diferente de 3.299999


---
Lembrar que x tem 16 algarismos significativos (precisos), logo devemos ter um erro numérico (epsilon) tal que:
\begin{align}
\epsilon = x \times 10^{-16}
\end{align}

Assim, sendo $C = 10^{-16}$ é a *constante de erro*

E a *variância* será então: $\sigma = Cx$

---

Dadas duas variáveis somadas ou subtraídas, $x_1$ e $x_2$, com variâncias $\sigma_1$ $\sigma_2$, então temos que:

\begin{align}
\\
\sigma^{2} = \sigma_1^{2} + \sigma_2^{2}
\\
\\
\Leftrightarrow \sigma = \sqrt{\sigma_1^{2} + \sigma_2^{2}}
\\
\\
\Leftrightarrow \sigma = \sqrt{C_1^{2} x_1^{2} + C_2^{2} x_2^{2}}
\end{align}

Já para o produto ou divisão de  duas variáveis, $x_1$ e $x_2$, tal que $x=x_1 x_2$ ou $x = \frac{x_1}{x_2}$ é:

\
\begin{align}
\sigma = \sqrt{2}Cx
\end{align}

Para uma soma $N$ variáveis, ${x_1,...,x_N}$ com variância, $\sigma_i = Cx_i$, então a variância total será:

\begin{align}
\sigma^2 = \sum_{i=1}^{N} \sigma_i^2 = \sum{i=1}^{N} C^2 x_i^2 = N C^2 \overline{x^2}
\end{align}

\begin{align}
\sigma = \sqrt{N} C \sqrt{\overline{x^2}}
\end{align}

Nota: $\sigma$ aumenta com o número de elementos combinados, $N$ elementos.

---

In [ ]:
#Se eu obter num cálculo 3.29999999999
x=3.2999999999

#Para verificar que x = 3.3

epsilon = 1e-6 # erro de arredondamento

if abs(x-3.3)<epsilon:
    print("x é igual a 3.3")

### Regra do Trapézio
A área da região abaixo dos pontos $f(x)$, tal que em $x \in [a,b]$ da função $f$ é dada por:

\
\begin{align}
I(a,b) = \int_{a}^{b} f(x) \, dx
\end{align}

---
Este é o valor exato da área nessa região. No entanto, computacionalmente este integral apenas pode ser resolvido por métodos numéricos como a *regra do trapézio*.

Primeiramente dividimo o intervalo $[a,b]$ em $N$ intervalos com um espaçamento $h= \frac{(b-a)}{N}$.

Assim sendo, teremos $N$ trapézios, sendo a área cada um deles dada por:

\
\begin{align}
A_k = \frac{h}{2}\left[f(a+(k-1)h) + f(a+kh)\right]
\end{align}

Nota: numeramos os trapézios por índices $k \in \{1,2,...,N\}$

Logo, podemos aproximar o integral de $a$ a $b$ por:
\
\begin{align}
\\
I(a,b) &\approx \sum_{k=1}^{N}A_k \\
&= \frac{h}{2} \sum_{k=1}^{N}\left[f(a+(k-1)h) + f(a+kh)\right] \\
&= h\left[\frac{1}{2}f(a) + f(a+h) + f(a+2h) + ... + \frac{1}{2}f(b)\right] \\
&= h\left[\frac{1}{2}f(a) + \frac{1}{2}f(b) + \sum_{k=1}^{N-1}f(a+kh)\right]
\end{align}

---


In [ ]:
# Algoritmo ideal para Regra do Trapézioo

def Trapezio(f,a,b,N): #f é a função que desejamos integrar
    h = (b-a)/N
    x = np.linspace(a,b,N)
    y = f(x)
    I = (h/2)*(y[0] + y[N-1] + 2*np.sum(y[1:N]))
    return I

#Exemplo:
def f(x):
    return x**4 - 2*x + 1
#Resultado:
print(Trapezio(f,0,2,10000))

### Regra de Simpson
Permite-nos calcular a área da região de maneira mais precisa, através de curvas quadráticas. No entanto, importante realçar que uma curva deste tipo necessita de 3 pontos, por isso vamos considerar que estes pontos estão espaçado por $h$.

Vamos ter os pontos $x_1=-h$, $x_2=0$ e $x_3=h$, a curva quadrática deverá seguir a forma: $Ax^2 + Bx + C$; e os valores de $f(x)$ serão:

\
\begin{align}
&f(-h) = Ah^2 - B h +C\\ \\&f(0) = C\\ \\&f(h) = Ah^2 + Bh + C      
\end{align}

Podemos concluir, então:

\
\begin{align}
&A = \frac{1}{h^2} \left[\frac{1}{2}f(-h) - f(0) + \frac{1}{2}f(h)\right] \\ \\&C = f(0)\\ \\&B = \frac{1}{2h} \left[f(h)-f(-h)\right]      
\end{align}

Nisto, a área de cada curva quadrática será dada por:

\
\begin{align}
\int_{-h}^{h} (Ax^2 + Bx + C)\, dx = \frac{2}{3}Ah^3 + 2Ch = \frac{1}{3}h \left[f(-h) + 4f(0) + f(h) \right]
\end{align}

Agora para obtermos o $I(a,b)$, necessitamos de somar todas as áreas das curvas quadráticas defenidas por 3 pontos:

\
\begin{align}
I(a,b) = \frac{h}{3} ( \left[ f(a) + 4f(a+h) + f(a+2h) \right] + \left[ f(a+2h) + 4f(a+3h) + f(a+4h) \right] \\ +   (...)    + \left[ f(a + (N-2)h) + 4f(a+(N-1)h) + f(b) \right] )
\end{align}

\
\begin{align}
I(a,b) &\approx \frac{h}{3} \left[ f(a) + 4f(a+h) + 2f(a+2h) + 4f(a+3h) + ... + f(b) \right]\\ &= \frac{h}{3} \left[ f(a) + f(b) + 4 \sum_{k\:ímpar}^{N-1} f(a+kh) +  2 \sum_{k\:par}^{N-2} f(a+kh) \right]
\end{align}

---

In [ ]:
#Algoritmo ideal para a Regra de Simpson

def Simpson(f,a,b,N):
    h=(b-a)/N
    x=np.linspace(a,b,N+1)
    y=f(x)
    I= h/3 * (y[0] + y[N] + 4*np.sum(y[1:N:2]) + 2*np.sum(y[2:N:2]))
    return I

#Exemplo:
def f(x):
    return x**4 - 2*x + 1
#Resultado:
print(Simpson(f,0,2,1000))

### Erro de aproximação 
Consideremos o integral de $x_k-1$ a $x_k$, expandindo $f(x)$ em série de Taylor, em torno do ponto $x_{k-1}$:

\
\begin{align}
f(x) = f(x_{k-1})+f'(x_{k-1})(x - x_{k-1}) + \frac{f''(x_{k-1}}{2!}(x - x_{k-1})^2
\end{align}

Assim, podemos calcular o integral a partir da série de Taylor:

\
\begin{align}
\int_{x_{k-1}}^{x_k} f(x) \, d(x) = f(x_{k-1})\int_{x_{k-1}}^{x_k}\,dx + f'(x_{k-1})\int_{x_{k-1}}^{x_k}(x - x_{k-1})\,dx + ...
\end{align}

Substituindo $u =x_k - x_{k-1}$:

\
\begin{align}
\int_{x_{k-1}}^{x_k} f(x) \, d(x) &= f(x_{k-1})\int_{0}^{h}\,du + f'(x_{k-1})\int_{0}^{h}u\,du + ...\\ &= hf(x_{k-1}) + \frac{h^2}{2}f'(x_{k-1}) + \frac{h^3}{6}f''(x_{k-1}) + O(h^4)
\end{align}


Podemos aplicar a integração a uma série de Taylor, desta vez em torno de $x_k$:

\
\begin{align}
\int_{x_{k-1}}^{x_k} f(x) \, d(x) &= hf(x_k) - \frac{h^2}{2}f'(x_k) + \frac{h^3}{6}f''(x_k) - O(h^4)
\end{align}

Considerando a média da integração das duas expansões, temos:

\
\begin{align}
\int_{x_{k-1}}^{x_k} f(x) \, d(x) &= \frac{h}{2} \left[ f(x_{k-1}) + f(x_k) \right] + \frac{h^2}{4} \left[ f'(x_{k-1}) - f'(x_k) \right] + \frac{h^3}{12} \left[ f''(x_{k-1}) + f''(x_k) \right] + O(h^4)
\end{align}

Agora somamos todas as fatias $k$ para obter o valor total do integral:

\
\begin{align}
\int_{a}^{b}f(x)\, dx &= \sum_{k=1}^{N} \int_{x_{k-1}}^{x_k} f(x)\, dx
\\ 
&= \frac{h}{2}\sum_{k=1}{N} \left[ f(x_{k-1}) + f(x_k) \right] + \frac{h^2}{4} \left[ f'(a) - f'(b) \right] + O(h^3)
\\
&= I_{T}(a,b) + O(h^3)
\end{align}

#### Nota 1:
A primeira soma do lado direito é equivalente à regra do trapézio.
#### Nota 2:
O resto da soma $O(h^3)$ é a quantidade necessária adicionar ao $I_t$ para obtermos o valor exato de $I(a,b)$, ou seja, é o erro de aproximação em relação ao uso da regra do trapézio.


Se substituirmos $f(x) \rightarrow f''(x)$, temos:

\
\begin{align}
\int_{a}^{b}f''(x)\, dx = \frac{h^2}{2} \sum_{k=1}^{N} \left[ f''(x_{k-1}) + f''(x_k) \right] + O(h^2)
\end{align}
\
Multiplicando por $\frac{h^2}{6}$, temos:

\
\begin{align}
\frac{h^2}{6} \int_{a}^{b} f''(x) \, dx + O(h^4) &= \frac{h^3}{12} \sum_{k=1}^{N} \left[ f''(x_{k-1}) + f''(x_k) \right]\\ &= \frac{h^2}{6} \left[ f'(b) - f'(a) \right] + O(h^4)
\end{align}

Conclusão:

\begin{align}
\int_{a}^{b} f(x) \, dx = \frac{h}{2} \sum_{k=1}^{N} \left[ f(x_{k-1}) + f(x_k) \right] + \frac{h^2}{12} \left[ f'(a) - f'(b) \right] + O(h^4)
\end{align}

E como: 

\begin{align}
I_T = \frac{h}{2} \sum_{k=1}^{N} \left[ f(x_{k-1}) + f(x_k) \right]
\end{align}

Então o erro aproximado que cometemos usando a regra do trapézio é:

\
\begin{align}
\epsilon = \frac{h^2}{12} \left[ f'(a) - f'(b) \right] + O(h^4)
\end{align}

Nota: não consideramos termos de maior ordem, ou seja, normalmente descarta-se $O(h^4)$

Além disto, temos o erro de arredondamento que terá um valor na ordem da constante $C=10^{-16}$ em Python

### Erro para a regra do trapézio
Na teoria poderiamos concluir que quanto menor o valor de $h$ (espaçamento entre trapézios), ou por outras palavras, quanto maior o valor de $N$ (números de intervalos), menor será o erro que iremos cometer e maior será a precisão da nossa integração numérica, mas isso não é verdade, pois quando:

\
\begin{align}
\epsilon = \frac{h^2}{12} \left[ f'(a) - f'(b) \right] \approx C \int_{a}{b}f(x) \, dx
\end{align}

Ou seja, se $diminuirmos\ h \implies \epsilon < C \int_{a}^{b}f(x) \, dx$, e portanto não iremos obter mais precisão e o nosso código será mais lento.

\
\begin{align}
h &= \sqrt{\frac{12 \int_{a}^{b} f(x) \, dx}{f'(a) - f'(b)}C}
\\
\\
N &= (b-a) \sqrt{{f'(a) - f'(b)}\frac{12 \int_{a}^{b} f(x) \, dx}C}
\end{align}




### Erro para a regra de Simpson
\
\begin{align}
\epsilon &= \frac{h^4}{90} \left[ f'''(a) - f'''(b) \right]
\\
\\
N &= (b-a) \sqrt[4]{\frac{f'''(a) - f'''(b)}{90 \int_{a}^{b} f(x) \, dx}} C^-1/4
\end{align}

Isto significa que o erro torna -se importante quando $N \approx 10000$

### Forma prática de estimar erros
Consideremos que vamos integrar em $x \in [a,b]$ e vamos usar a Regra do Trapézio, recorrendo a $N_1$ intervalos com $h_1 = (b-a) /N_1$.

\
Agora consideremos que faremos a mesma integração mas agora em $N_2$ intervalos, tal que $N_2 = 2N_1$, com $h_2=(b-a)/N_2 \Rightarrow h_2 = 2h_1$.

\
É importante relembrar que a Regra do Trapézio introduz um erro de $O(h^2)$, o que significa que se tivermos $\frac{h}{2}$, então temos um erro de $\frac{O (h^2)}{4}$. Ou seja, facilmente verficamos que: maior o número de intervalos $N$ $\Rightarrow$ menor $h$ $\Rightarrow$ maior erro.

\
Consideremos o valor exato do integral $I$, sendo $I - I_T = \epsilon$ (erro), que é porporcional a $h^2$, portanto $\epsilon = ch^2$, com $c$ sendo uma constante.


###### Nota: todos os termos relacionados com $N_1$ e $N_2$, são atribuídos $1$ e $2$ respetivamente.
\
Temos então que:
\begin{align}
I_{1} + ch_{1}^2 &= I_2 + ch_2^2\\ \\I_{2} - I_1 &= ch_{1}^2 - ch_2^2 = 3ch_2^2
\end{align}

\
Além disso:
\
\begin{align}
\epsilon_2 = ch_2^2 = \frac{1}{3}(I_2 - I_1)
\end{align}

#### Para a Regra de simpson:
\begin{align}
\epsilon_2 =\frac{1}{15} (I_2-I_1)
\end{align}

### Encontrar o melhor nº de intervalos
Consideremos que usamos a Regra do Trapézio com $N_i$ intervalos e com $h_i = (b-a)/N_i$, lembrando que $N_{i-1} = \frac{1}{2}N_i$ e $h_{i-1} = 2h_i$. Então:

\
\begin{align}
I_i &= h_i \left[ \frac{f(a)}{2} + \frac{f(b)}{2} + \sum_{k=1}^{N_i-1} f(a+kh_i) \right]\\ &= h_i \left[ \frac{f(a)}{2} + \frac{f(b)}{2} + \sum_{k\,par}^{N_i-2} f(a+kh_i) + \sum_{k\,ímpar}^{N_i-1} f(a+kh_i) \right]
\end{align}

Verificamos no entanto que:

\
\begin{align}
\sum_{k\,par}^{N_i-2}f(a+2kh_i) = \sum_{k=1}^{N_i/2 - 1} = \sum_{k=1}^{N_{i-1}-1}f(a+kh_{i-1}
\end{align}

O que implica:

\begin{align}
I_i = \frac{h_{i-1}}{2} \left[ \frac{f(a)}{2} + \frac{f(b)}{2} + \sum_{k=1}^{N_{i-1}-1} f(a+kh_{i-1}) \right] + h_i \sum_{k\, ímpar}^{N_i-1}f(a+kh_i)
\end{align}

Nota: o primeiro termo é precisamente o $I_{i-1}$ dado pela regra do Trapézio, por isso...

\
\begin{align}
I_i = \frac{I_{i-1}}{2} + h_i \sum_{k\, ímpar}^{N_i-1}f(a+kh_i)
\end{align}

Ou seja, o integral $I_i$ dado por $N_i$ intervalos não precisa de ser calculado do zero, tornando o processo computacional mais rápido e preciso, pois podemos apenas necessitamos calcular uma parte, sendo que a outra é dada pelo integral anterior, $I_{i-1}$ e por $N_{i-1}$ intervalos

### Equivalente para a Regra de Simpson
\
O erro é dado por: $\epsilon_i = \frac{(I_i - I_{i-1})}{15}$; logo:
\begin{align}
&S_i = \frac{1}{3} \left[ f(a) + f(b) + 2 \sum_{k\,par}{N_i-2} f(a+kh_i) \right]\\ \\&T_i = \frac{2}{3} \sum_{k\,ímpar}^{N_i-1} f(a+kh_i)\\ \\&\Rightarrow S_i = S_{i-1} + T_{i-1} \land I_i = h_i(S_i + 2T_i) 
\end{align}

## Integração de Romberg

Voltando à regra do Trapézio, o erro é da ordem $ch_i^2 = \frac{(I_i - I_{i-1})}{3}$, sendo que por definição ,$I = I_i + ch_i^2 + O(h_i^4) = I_i + \frac{1}{3}(I_i-I_{i-1}) + O(h_i^4)$

Vamos dizer que:
\
\begin{align}
&R_{i,1} = I_i\,\,\,\,\,\,\,\,\,\,\,\,\,\,\,\,\,\, R_{i,2}=I_i + \frac{1}{3}(I_i - I_{i-1}) = R_{i,1} + \frac{1}{3}(R_{i,1} - R_{i-1,1})\\ \\&\Rightarrow I = R_{i,2} + c_2h_i^4 + O(h_i)^6 = R_{i-1,2} + c_2h_{i-1}^4 + O(h_{i-1}^6) = R_{i-1,2} + 16c_2h_i^4 + O(h_i^6)
\end{align}

Daqui tiramos que:
\
\begin{align}
c_2h_i^4 = \frac{1}{15}(R_{i,2} - R_{i-1,2}) + O(h_i^6)\,\,\,\,\, \Rightarrow\,\,\,\,\,I = R_{i,2} + \frac{1}{15}(R_{i,2} - R_{i-1,2}) + O(h_i^6)
\end{align}

Em suma:

\
\begin{align}
I &= R_{i,m+1} + O(h_i^{2m+2})\\ R_{i,m+1} &= R_{i,m} + \frac{1}{4^m-1}(R_{i,m} - R_{i-1,m})
\end{align}

Lembrando que $R_{i,1} = I_i$.

In [ ]:
#Algoritmo ideal para Romberg

def Romberg(f,a,b,N):
    R = np.zeros((N, N))
    R[0,0] = Trapezio(f,a,b,N)
    tol = 1e-6
    erro = 1 
    i = 1
    while erro>tol:
        N*=2
        R[i,0]=Trapezio(f,a,b,N)
        for j in range(1,i+1):
            R[i,j] = (R[i,j-1] + 1/(4**(j)-1) * (R[i,j-1] - R[i-1,j-1]))
        erro = abs(R[i,i] - R[i-1,i-1])
        i+=1
    return R[i-1,i-1] , erro , i , N

#Exemplo:
def f(x):
    return x**4 - 2*x + 1
#Resultado:
print(Romberg(f,0,2,100))


## Quadratura Gaussiana

Vamos supor que temos $N$ pontos $x_k$, vamos então calcular o integral de $\int_{a}^{b} f(x)\,dx \approx \sum_{k=1}^{N}w_kf(x_k)$ baseando-nos nos pontos $f(x_k)$ e usando pesos $w_k$.

Para obter estes $N$ pontos, necessitamos um polinómio de grau $N-1$, dado por um polinómio de interpolação:

\
\begin{align}
\phi_k(x) &= \prod_{m=1\, \land\, m \neq k}^{N} \frac{(x-x_m)}{(x_k-x_m)}\\ \\&=\frac{(x-x_1)}{(x_k-x_1)}\, \times\, (...)\, \times\, \frac{(x-x_{k-1})}{(x_k-x_{k-1})}\, \times\, \frac{(x-x_{k+1})}{(x_k-x_{k+1})}\, \times\, (...)\, \times\, \frac{(x-x_{N})}{(x_k-x_{N})}
\end{align}

Resumindo:

\
\begin{align}
\phi_k(x_m) = \delta _{km} =\left\{
    \begin{array}{ll}
        1 & \text{se } m=k \\
        0 & \text{se } m \neq k
    \end{array}
\right.
\end{align}

O $\delta_{km}$ é o delta de Knronecker.\\

É importante saber que este polinómio \Phi(x) de grau $N-1$ é único para $N$ pontos de $f(x)$ e é uma combinação linear de polinómios também de grau $N-1$ como veremos a seguir:

\
\begin{align}
\Phi(x_m) = \sum_{k=1}^{N} f(x_k)\phi_k(x) = \sum_{k=1}^{N} f(x_k) \delta_{km} = f(x_m)
\end{align}

Para calcular a aproximação do nosso integral:

\
\begin{align}
\int_{a}^{b} f(x) \, dx \approx \int_{a}^{b} \phi(x) \, dx = \int_{a}^{b} \sum_{k=1}^{N} f(x_k) \phi_k(x) \,dx = \sum_{k=1}^{N} f(x_k) \int_{a}^{b} \phi_k(x) \,dx
\end{align}

Note-se que $\int_{a}^{b} \phi_k(x) \,dx = w_k$ chamamos de pesos.

Além disso, poderemos ter um outro problema ao integrar numéricamente a função, através de pesos e zeros, ou seja, através da quadratura de Gauss: os limites de integração. Por norma, temos $w_k = \int_{-1}^{1} \phi_k(x) \,dx$. Mas podemos mudar os limites de integração da seguinte forma:

\
\begin{align}
x_k' &= \frac{1}{2}(b-a)x_k + \frac{1}{2}(b+a)\\
w_k' &= \frac{1}{2}(b-a)w_k
\end{align}

Daí tiramos que:

\
\begin{align}
\int_{a}^{b} f(x)\, dx \approx \sum_{k=1}^{n}w_k'f(x_k')
\end{align}

In [30]:
#Algortimo de exemplo para a Quadratura de Gauss-Legendre:

def f(x):
    return x**2

def gauss(f,a,b,N):
    zeros, pesos = scipy.special.roots_legendre(N)
    zeros = 0.5*(b-a)*zeros + 0.5*(b+a)
    pesos = 0.5*(b-a)*pesos
    I = np.sum(f(zeros)*pesos)
    return I

print(gauss(f,-1,1,1000))

#Algortimo de exemplo para a Quadratura de Gauss-Hermite:

def hermite(f,N):
    zeros, pesos = scipy.special.roots_hermite(N)
    I = np.sum(f(zeros)*pesos)
    return I

print(hermite(f,100000))

#Algortimo de exemplo para a Quadratura de Gauss-Chebyshev:

def chebyshev(f,a,b,N):
    zeros, pesos =  scipy.special.roots_chebyt(N)
    x = 0.5*(b-a)*zeros + 0.5*(b+a)
    pesos = 0.5*(b-a)*pesos
    I = np.sum(f(x)*pesos*np.sqrt(1-zeros**2))
    return I
    
print(chebyshev(f,-1,1,1000))

0.6666666666663987
0.8862269254525016
0.6666674891353576


## Soluções de sistemas de equações lineares / não lineares

Iremos encontrar matrizes da forma:
\
\begin{align}
\textbf{A}\textbf{x} = \textbf{v}
\end{align}


### Eliminação de Gauss

Este é um método no qual procuramos transforma a nossa matriz $\textbf{A}$ numa matriz triangular superior:
\
\
\begin{align}
Matriz\,\,\,\,triangular\,\,\,\,superior =  \begin{bmatrix}
a_{11} & a_{12} & a_{13} & \cdots & a_{1n} \\
0 & a_{22} & a_{23} & \cdots & a_{2n} \\
0 & 0 & a_{33} & \cdots & a_{3n} \\
\vdots & \vdots & \vdots & \ddots & \vdots \\
0 & 0 & 0 & \cdots & a_{nn} \\
\end{bmatrix}
\end{align}

Note-se que:
\
\begin{align}
x_n = \frac{b_n}{a_{n,n}} \implies x_{n-1} = \frac{b_{n-1}-a_{n-1,n}x_n}{a_{n-1,n-1}} \implies\,\,\, ...\,\,\, \implies x_{n-i}
= \frac{b_{n-i} - \sum_{i-1}^{j=0}\, a_{n-i,n-j}x_{n-j}}{a_{n-i,n-i}},\,\,\,\, i\leq i \leq n-1
\end{align}

In [25]:
#Algoritmo de resolução de matrizes triangulares superiores n x n

def Resolve_tri_sup (A,v):
    n=len(v)
    x=np.zeros(n)
    x[n-1]=v[n-1]/A[n-1][n-1]
    for i in range(n-1,0,-1):
        s=0
        for j in range(i+1,n+1,1):
            s= s + A[i-1][j-1]*x[j-1]
        x[i-1]= (v[i-1]-s)/A[i-1][i-1]
    return x

A=[[3,2,4],[0,1/3,2/3],[0,0,-8]]
v=[1, 5/3,0]

print(Resolve_tri_sup(A,v))
print(np.linalg.solve(A, v))

[-3.  5. -0.]
[-3.  5. -0.]


In [24]:
#1º Código da eleminação de Gauss:

def resolve_gauss(A, v):
    N = len(v)
    x = np.zeros(N)
    for p in range(N):
        for i in range(p+1, N):
            coef = A[i,p]/A[p,p]
            v[i] -= v[p] * coef
            for j in range(p, N):  # Corrigindo o índice de início do loop
                A[i,j] -= coef * A[p,j]
        print("Pivo: ", p,"\n Matriz: ", A, "\n")

    for p in range(N-1, -1, -1):
        x[p] = v[p]
        for i in range(p+1, N):
            x[p] -= A[p,i]*x[i]
        x[p] = x[p]/A[p,p]
    return x

A = np.array([[0.1,1,2,4.1],[3,4.1,5,2], [6,7,8,5], [0.5,0,3,5]])
v = np.array([0.1,0.2,0.3,0.4])
x = resolve_gauss(A.copy(), v.copy())

print("Solução x:", x)
print(np.linalg.solve(A, v))

Pivo:  0 
 Matriz:  [[ 1.00e-01  1.00e+00  2.00e+00  4.10e+00]
 [ 0.00e+00 -2.59e+01 -5.50e+01 -1.21e+02]
 [ 0.00e+00 -5.30e+01 -1.12e+02 -2.41e+02]
 [ 0.00e+00 -5.00e+00 -7.00e+00 -1.55e+01]] 

Pivo:  1 
 Matriz:  [[ 1.00000000e-01  1.00000000e+00  2.00000000e+00  4.10000000e+00]
 [ 0.00000000e+00 -2.59000000e+01 -5.50000000e+01 -1.21000000e+02]
 [ 0.00000000e+00 -7.10542736e-15  5.48262548e-01  6.60617761e+00]
 [ 0.00000000e+00  0.00000000e+00  3.61776062e+00  7.85907336e+00]] 

Pivo:  2 
 Matriz:  [[ 1.00000000e-01  1.00000000e+00  2.00000000e+00  4.10000000e+00]
 [ 0.00000000e+00 -2.59000000e+01 -5.50000000e+01 -1.21000000e+02]
 [ 0.00000000e+00 -7.10542736e-15  5.48262548e-01  6.60617761e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -3.57323944e+01]] 

Pivo:  3 
 Matriz:  [[ 1.00000000e-01  1.00000000e+00  2.00000000e+00  4.10000000e+00]
 [ 0.00000000e+00 -2.59000000e+01 -5.50000000e+01 -1.21000000e+02]
 [ 0.00000000e+00 -7.10542736e-15  5.48262548e-01  6.60617761e+00]
 [

In [26]:
#2º código possível para a eliminação de gauss e solução da matriz

def resolve_gauss_2(A,v):
    N=len(v)
    x = np.zeros(N)
    for p in range(N):
        for i in range(p+1,N):
            v[i] -= v[p] * A[i][p]/A[p][p]
            A[i, p:] -= A[p, p:] * A[i,p]/A[p,p]
    print(A)
    for p in range(N-1,-1,-1):
        x[p] = (v[p] -np.dot(A[p, p+1:], x[p+1:]))/A[p,p]
    return x

A = np.array([[0.1,1,2,4.1],[3,4.1,5,2], [6,7,8,5], [0.5,0,3,5]])
v = np.array([0.1,0.2,0.3,0.4])
x = resolve_gauss_2(A.copy(), v.copy())

print("Solução x:", x)
print("Resíduo Ax - v:", np.dot(A, x) - v)
print(np.linalg.solve(A, v))

[[ 1.00000000e-01  1.00000000e+00  2.00000000e+00  4.10000000e+00]
 [-4.44089210e-16 -2.59000000e+01 -5.50000000e+01 -1.21000000e+02]
 [-8.88178420e-16 -7.10542736e-15  5.48262548e-01  6.60617761e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -3.57323944e+01]]
Solução x: [ 0.04862042 -0.15007883  0.13662791 -0.00683879]
Resíduo Ax - v: [ 0.00000000e+00  5.55111512e-17 -1.83186799e-15  1.11022302e-16]
[ 0.04862042 -0.15007883  0.13662791 -0.00683879]


### Eliminação Gauss-Jordan

In [27]:
#1º código para eliminação Gauss-Jordan
def gauss_jordan(A,v):
    N = len(v)
    for p in range(N):
        v[p] /= A[p,p]
        A[p,p:] /= A[p,p]
        for i in range(p):
            v[i] -= v[p]*A[i,p]
            A[i,p:] -= A[p,p:] * A[i,p]
        for i in range(p+1, N):
            v[i] -=v[p] * A[i,p]
            A[i,p:] -= A[p,p:] * A[i,p]
        print("Pivot: " ,p,"\n Matirz: ", A)
    return v

A = np.array([[0.1,1,2,4.1],[3,4.1,5,2], [6,7,8,5], [0.5,0,3,5]])
v = np.array([0.1,0.2,0.3,0.4])
x = gauss_jordan(A.copy(), v.copy())

print("Solução x:", x)
print(np.linalg.solve(A, v))

Pivot:  0 
 Matirz:  [[   1.    10.    20.    41. ]
 [   0.   -25.9  -55.  -121. ]
 [   0.   -53.  -112.  -241. ]
 [   0.    -5.    -7.   -15.5]]
Pivot:  1 
 Matirz:  [[ 1.          0.         -1.23552124 -5.71814672]
 [ 0.          1.          2.12355212  4.67181467]
 [ 0.          0.          0.54826255  6.60617761]
 [ 0.          0.          3.61776062  7.85907336]]
Pivot:  2 
 Matirz:  [[  1.           0.           0.           9.16901408]
 [  0.           1.           0.         -20.91549296]
 [  0.           0.           1.          12.04929577]
 [  0.           0.           0.         -35.73239437]]
Pivot:  3 
 Matirz:  [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Solução x: [ 0.04862042 -0.15007883  0.13662791 -0.00683879]
[ 0.04862042 -0.15007883  0.13662791 -0.00683879]


In [28]:
#2º código para a eliminação de Gauss-Jordan

def gauss_jordan_2(A,v):
    N = len(v)
    A_new = np.zeros([N , N+1])
    A_new[:, :N] = A
    A_new[:, N] = v
    
    for p in range(N):
        A_new[p,p:] /= A_new[p,p]
        
        for i in range(p):
            A_new[i,p:] -= A_new[p,p:] * A_new[i,p]
        for i in range(p+1, N):
            A_new[i,p:] -= A_new[p,p:] * A_new[i,p]
    return A_new[:, -1]

A = np.array([[0.1,1,2,4.1],[3,4.1,5,2], [6,7,8,5], [0.5,0,3,5]])
v = np.array([0.1,0.2,0.3,0.4])
x = gauss_jordan_2(A.copy(), v.copy())

print("Solução x:", x)
print(np.linalg.solve(A, v))

Solução x: [ 0.04862042 -0.15007883  0.13662791 -0.00683879]
[ 0.04862042 -0.15007883  0.13662791 -0.00683879]


### Eliminação de Gauss-Jordan com recuso a pivotagem parcial

In [29]:
#1º código gauss-jordan com pivotagem parcial e com recurso a um array para a troca das linhas
def gauss_jordan_pivparcial(A,b):
    N = len(b)
    linhas = np.arange((N))
    AA = np.zeros((N, N+1))
    AA[:N ,:N] = A
    AA[:,N]=b
    
    for p in range(N):
        indice = np.argmax(np.abs(AA[linhas[p:], p])) + p
        linhas[p], linhas[indice] = linhas[indice], linhas[p]
        AA[linhas[p], : ] /= AA[linhas[p], p]
        
        for i in range(p):
            AA[linhas[i], p:] -= AA[linhas[p], p:]*AA[linhas[i], p]
        
        for i in range(p+1,N):
            AA[linhas[i], p:] -= AA[linhas[p], p:]*AA[linhas[i], p]
        print("\nArray linhas (troca de linhas):\n", linhas,"\n Matriz A:\n", A)
        
    return AA[linhas[:], -1]

A = np.array([[0.1,1,2,4.1],[3,4.1,5,2], [6,7,8,5], [0.5,0,3,5]])
v = np.array([0.1,0.2,0.3,0.4])
x = gauss_jordan_pivparcial(A.copy(), v.copy())

print("Solução x:", x)
print(np.linalg.solve(A, v))


Array linhas (troca de linhas):
 [2 1 0 3] 
 Matriz A:
 [[0.1 1.  2.  4.1]
 [3.  4.1 5.  2. ]
 [6.  7.  8.  5. ]
 [0.5 0.  3.  5. ]]

Array linhas (troca de linhas):
 [2 0 1 3] 
 Matriz A:
 [[0.1 1.  2.  4.1]
 [3.  4.1 5.  2. ]
 [6.  7.  8.  5. ]
 [0.5 0.  3.  5. ]]

Array linhas (troca de linhas):
 [2 0 3 1] 
 Matriz A:
 [[0.1 1.  2.  4.1]
 [3.  4.1 5.  2. ]
 [6.  7.  8.  5. ]
 [0.5 0.  3.  5. ]]

Array linhas (troca de linhas):
 [2 0 3 1] 
 Matriz A:
 [[0.1 1.  2.  4.1]
 [3.  4.1 5.  2. ]
 [6.  7.  8.  5. ]
 [0.5 0.  3.  5. ]]
Solução x: [ 0.04862042 -0.15007883  0.13662791 -0.00683879]
[ 0.04862042 -0.15007883  0.13662791 -0.00683879]


In [30]:
#2º código de gauss-jordan com pivotagem parcial
# e com recurso a uma matriz I identidade para as trocas
def gauss_jordan_pivpartial(A, b):
    N = len(b)
    P = np.eye(N)
    AA = np.zeros((N, N+1))
    AA[:, :-1] = A  # Corrigindo a definição de AA
    AA[:, -1] = b
    
    for p in range(N):
        indice = np.argmax(np.abs(AA[p:, p])) + p
        P[[p, indice]] = P[[indice, p]]
        AA[[p, indice]] = AA[[indice, p]]
        AA[p] /= AA[p, p]

        for i in range(N):
            if i != p:
                AA[i] -= AA[p] * AA[i, p]
        print("\nMatriz P (troca de linhas):\n", P,"\n Matriz A:\n", A)
        
    return AA[:, -1]

A = np.array([[0.1,1,2,4.1],[3,4.1,5,2], [6,7,8,5], [0.5,0,3,5]])
v = np.array([0.1,0.2,0.3,0.4])
x = gauss_jordan_pivpartial(A.copy(), v.copy())

print("Solução x:", x)
print(np.linalg.solve(A, v))


Matriz P (troca de linhas):
 [[0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]] 
 Matriz A:
 [[0.1 1.  2.  4.1]
 [3.  4.1 5.  2. ]
 [6.  7.  8.  5. ]
 [0.5 0.  3.  5. ]]

Matriz P (troca de linhas):
 [[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]] 
 Matriz A:
 [[0.1 1.  2.  4.1]
 [3.  4.1 5.  2. ]
 [6.  7.  8.  5. ]
 [0.5 0.  3.  5. ]]

Matriz P (troca de linhas):
 [[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]] 
 Matriz A:
 [[0.1 1.  2.  4.1]
 [3.  4.1 5.  2. ]
 [6.  7.  8.  5. ]
 [0.5 0.  3.  5. ]]

Matriz P (troca de linhas):
 [[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]] 
 Matriz A:
 [[0.1 1.  2.  4.1]
 [3.  4.1 5.  2. ]
 [6.  7.  8.  5. ]
 [0.5 0.  3.  5. ]]
Solução x: [ 0.04862042 -0.15007883  0.13662791 -0.00683879]
[ 0.04862042 -0.15007883  0.13662791 -0.00683879]


### Elimação Gauss Jordan com pivotagem total

In [31]:
def gauss_jordan_pivtotal(A,b):
    N = len(b)
    linhas = np.arange(N)
    colunas = np.arange(N+1)
    AA = np.zeros((N,N+1))
    AA[:N, :N] = A
    AA[: , N] = b
    aa = np.zeros(N*N)
    
    for p in range(N):
        m = N-p
        for i in range(m):
            aa[i * m:(i+1) * m] = AA[linhas[p+i], colunas[p:-1]]
        indice = np.argmax(np.abs(aa[:m * m]))
        l = p + indice//m
        c = p + indice % m 
        linhas[p], linhas[l] = linhas[l], linhas[p]
        colunas[p], colunas[c] = colunas[c], colunas[p]
        AA[linhas[p], colunas[:]] /= AA[linhas[p], colunas[p]]
        for i in range(p):
            AA[linhas[i], colunas[p:]] -= AA[linhas[p], colunas[p:]]*AA[linhas[i], colunas[p]]
        for i in range(p+1, N):
            AA[linhas[i], colunas[p:]] -= AA[linhas[p], colunas[p:]]*AA[linhas[i], colunas[p]]
    return AA[colunas[linhas[ : ]] , -1]
    
A = np.array([[0.1,1,2,4.1],[3,4.1,5,2], [6,7,8,5], [0.5,0,3,5]])
v = np.array([0.1,0.2,0.3,0.4])
x = gauss_jordan_pivtotal(A.copy(), v.copy())

print("Solução x:", x)
print(np.linalg.solve(A, v))

Solução x: [ 0.04862042 -0.15007883  0.13662791 -0.00683879]
[ 0.04862042 -0.15007883  0.13662791 -0.00683879]


### Matriz inversa por Gauss-Jordan

In [23]:
#Código de inversão Gauss-Jordan

def gauss_jordan_inverse(A):
    n = len(A)
    # Criar uma matriz identidade do mesmo tamanho que A
    I = np.eye(n)
    # Concatenar a matriz A com a matriz identidade
    AI = np.concatenate((A, I), axis=1)

    # Aplicar eliminação de Gauss-Jordan
    for i in range(n):
        print(AI)
        # Dividir a linha i pela diagonal principal para obter um 1 na diagonal principal
        AI[i] /= AI[i, i]
        
        # Subtrair múltiplos da linha i de outras linhas para zerar os elementos abaixo e acima da diagonal principal
        for j in range(n):
            if i != j:
                AI[j] -= AI[i] * AI[j, i]
    # A inversa está na segunda parte da matriz AI
    inverse = AI[:, n:]

    return inverse

A=np.array([[1,2,1],[3,-2,-2],[1,3,-1]],float)
print(gauss_jordan_inverse(A))
print(np.linalg.inv(A))

[[ 1.  2.  1.  1.  0.  0.]
 [ 3. -2. -2.  0.  1.  0.]
 [ 1.  3. -1.  0.  0.  1.]]
[[ 1.  2.  1.  1.  0.  0.]
 [ 0. -8. -5. -3.  1.  0.]
 [ 0.  1. -2. -1.  0.  1.]]
[[ 1.     0.    -0.25   0.25   0.25   0.   ]
 [-0.     1.     0.625  0.375 -0.125 -0.   ]
 [ 0.     0.    -2.625 -1.375  0.125  1.   ]]
[[ 0.38095238  0.23809524 -0.0952381 ]
 [ 0.04761905 -0.0952381   0.23809524]
 [ 0.52380952 -0.04761905 -0.38095238]]
[[ 0.38095238  0.23809524 -0.0952381 ]
 [ 0.04761905 -0.0952381   0.23809524]
 [ 0.52380952 -0.04761905 -0.38095238]]


### Eliminação de Gauss com pivotamento parcial

O pivotamento parcial consiste na troca entre linhas de forma a favorecer a eliminação de Gauss. Para o último método referido necessitamos que  a matriza $\textbf{A}$ seja uma triangular superior, ou seja, temos que:

\
\begin{align}
a_{i,j} \neq 0 ,\,\,\, i \leq j\,\,  \land\,\, a_{i,j} = 0 ,\,\,\, i > j
\end{align}

Mas, por vezes, o que acontece é que temos elementos $a_{i,j} = 0$ com $i \leq j$ o que nos impossibilita de implementar a eliminação de Gauss. Daí a troca de linhas, ou seja, o pivotamento parcial.

In [32]:
#1º Código para eliminação de Gauss com pivotamento parcial

A=np.array([[1,2,1],[3,-2,-2],[1,3,-1]],float)
v=np.array([1,-1,-9],float)

def eli_gaus_compiv(A,v):
    
    N=len(v)
    x = np.empty(N, float)
    
    for m in range(N):
        
        # Encontre o índice do elemento com o maior valor absoluto na coluna atual
        k = np.argmax(np.abs(A[m:, m])) + m
        
        # Troque as linhas para colocar o elemento pivot na diagonal principal
        A[[m, k], :] = A[[k, m], :]
        v[[m, k]] = v[[k, m]]
        
        # Eliminação gaussiana
        for i in range(m+1, N):
            factor = A[i, m] / A[m, m]
            A[i, :] -= factor * A[m, :]
            v[i] -= factor * v[m]
        
        
    # Substituição retroativa
    for m in range(N-1, -1, -1):
        x[m] = v[m]
        for i in range(m+1, N):
            x[m] -= A[m, i] * x[i]
        x[m] /= A[m, m]
    return x

print(eli_gaus_compiv(A,v))
print(np.linalg.solve(A, v))

[ 1. -2.  4.]
[ 1. -2.  4.]


In [36]:
#2º Código de eliminação de Gauss com pivotamento parcial

A=np.array([[1,2,1],[3,-2,-2],[1,3,-1]],float)
v=np.array([1,-1,-9],float)

def gauss_pivotpartial(A,v):
    N=len(A)
    i=0
    x=np.empty(N, float)
    
    while i<N:
        #Pivotamento parcial
        for p in range (i+1,N):
            if abs(A[i,i]) < abs(A[p,i]):
                A[[p,i]] = A[[i,p]]
                v[[p, i]] = v[[i, p]]
                print(A)
        
        
        for j in range(i+1, N):
            fact = A[j,i]/A[i,i]
            A[j , : ] -= fact*A[i, :]
            v[j] -= fact*v[i]
        i+=1
    
    for m in range(N-1, -1, -1):
        x[m] = v[m]
        for i in range(m+1, N):
            x[m] -= A[m, i] * x[i]
        x[m] /= A[m, m]
    return x

def gauss_pivotpartial(A, v):
    N = len(A)
    x = np.empty(N, float)
    i = 0
    
    while i < N:
        # Pivotamento parcial
        for p in range(i + 1, N):
            if abs(A[i, i]) < abs(A[p, i]):
                print("Troca de linhas: \nAntes:\n", A)
                A[[p, i]] = A[[i, p]]
                v[[p, i]] = v[[i, p]]
                print("Depois:\n", A)
        
        for j in range(i + 1, N):
            fact = A[j, i] / A[i, i]
            A[j, :] -= fact * A[i, :]
            v[j] -= fact * v[i]
        i += 1
    
    for m in range(N - 1, -1, -1):
        x[m] = v[m]
        for i in range(m + 1, N):
            x[m] -= A[m, i] * x[i]
        x[m] /= A[m, m]
    
    return x

# Exemplo de uso:
x = gauss_pivotpartial(A, v)
print("Solução:", x)
A=np.array([[1,2,1],[3,-2,-2],[1,3,-1]],float)
v=np.array([1,-1,-9],float)

print(np.linalg.solve(A, v))

Troca de linhas: 
Antes:
 [[ 1.  2.  1.]
 [ 3. -2. -2.]
 [ 1.  3. -1.]]
Depois:
 [[ 3. -2. -2.]
 [ 1.  2.  1.]
 [ 1.  3. -1.]]
Troca de linhas: 
Antes:
 [[ 3.         -2.         -2.        ]
 [ 0.          2.66666667  1.66666667]
 [ 0.          3.66666667 -0.33333333]]
Depois:
 [[ 3.         -2.         -2.        ]
 [ 0.          3.66666667 -0.33333333]
 [ 0.          2.66666667  1.66666667]]
Solução: [ 1. -2.  4.]
[ 1. -2.  4.]


In [37]:
# código de elimação de gauss com pivotamento parcial com recurso a uma matriz I identidade para as permutações das linhas
def gauss_elimination_piv(A, b):
    n = len(b)
    P = np.eye(n)  # Matriz de permutações inicialmente identidade
    
    for j in range(n-1):
        # Encontrar o índice da linha com o maior valor na coluna atual
        max_row_index = np.argmax(abs(A[j:, j])) + j
        
        # Trocar a linha atual com a linha encontrada
        if max_row_index != j:
            print(A)
            print(P)
            A[[j, max_row_index]] = A[[max_row_index, j]]
            b[[j, max_row_index]] = b[[max_row_index, j]]
            P[[j, max_row_index]] = P[[max_row_index, j]]
        
        # Eliminação gaussiana
        for i in range(j+1, n):
            factor = A[i, j] / A[j, j]
            A[i, j:] -= factor * A[j, j:]
            b[i] -= factor * b[j]

    # Resolvendo o sistema triangular superior
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = (b[i] - np.dot(A[i, i+1:], x[i+1:])) / A[i, i]
    
    return x, P

# Exemplo de uso
A=np.array([[1,2,1],[3,-2,-2],[1,3,-1]],float)
v=np.array([1,-1,-9],float)


x, P = gauss_elimination_piv(A, v)
print("Solução:", x)
print("Matriz de Permutações:\n", P)
A=np.array([[1,2,1],[3,-2,-2],[1,3,-1]],float)
v=np.array([1,-1,-9],float)
print(np.linalg.solve(A, v))

[[ 1.  2.  1.]
 [ 3. -2. -2.]
 [ 1.  3. -1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[ 3.         -2.         -2.        ]
 [ 0.          2.66666667  1.66666667]
 [ 0.          3.66666667 -0.33333333]]
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
Solução: [ 1. -2.  4.]
Matriz de Permutações:
 [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[ 1. -2.  4.]


In [41]:
#Código com eliminação de gauss e pivotamento total

A=np.array([[1,2,1],[3,-2,-2],[1,3,-1]],float)
v=np.array([1,-1,-9],float)

def gauss_elimination_pivot(A, b):
    n = len(A)
    indexes = np.arange(n)
    print("Matriz A Inicial:\n", A)
    # Forward Elimination with Total Pivoting
    for i in range(n):
        # Total pivoting
        pivot_row, pivot_col = np.unravel_index(np.abs(A[i:, i:]).argmax(), A[i:, i:].shape)
        pivot_row += i
        pivot_col += i
        max_value = A[pivot_row, pivot_col]
        for k in range(i + 1, n):
            for l in range(i, n):
                if abs(A[k, l]) > max_value:
                    pivot_row, pivot_col = k, l
                    max_value = A[pivot_row, pivot_col]
        print("Pivô encontrado:", A[pivot_row, pivot_col])
        
        # Swap rows
        if pivot_row != i:
            A[[i, pivot_row]] = A[[pivot_row, i]]
            b[[i, pivot_row]] = b[[pivot_row, i]]
            indexes[[i, pivot_row]] = indexes[[pivot_row, i]]
            print("Troca de linhas - Matriz A:\n", A)
        
        # Swap columns
        if pivot_col != i:
            A[:, [i, pivot_col]] = A[:, [pivot_col, i]]
            print("Troca de colunas - Matriz A:\n", A)
            
        # Elimination
        for j in range(i + 1, n):
            factor = A[j, i] / A[i, i]
            for k in range(i, n):
                A[j, k] -= factor * A[i, k]
            b[j] -= factor * b[i]
        print("Após eliminação - Matriz A:\n", A)

    # Back substitution
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = b[i]
        for j in range(i + 1, n):
            x[i] -= A[i, j] * x[j]
        x[i] /= A[i, i]
    print("Solução encontrada:", x)

    # Return the solution
    return x


# Exemplo de uso:

print(gauss_elimination_pivot(A, v))
A=np.array([[1,2,1],[3,-2,-2],[1,3,-1]],float)
v=np.array([1,-1,-9],float)
print(np.linalg.solve(A,v))

Matriz A Inicial:
 [[ 1.  2.  1.]
 [ 3. -2. -2.]
 [ 1.  3. -1.]]
Pivô encontrado: 3.0
Troca de linhas - Matriz A:
 [[ 3. -2. -2.]
 [ 1.  2.  1.]
 [ 1.  3. -1.]]
Após eliminação - Matriz A:
 [[ 3.         -2.         -2.        ]
 [ 0.          2.66666667  1.66666667]
 [ 0.          3.66666667 -0.33333333]]
Pivô encontrado: 3.6666666666666665
Troca de linhas - Matriz A:
 [[ 3.         -2.         -2.        ]
 [ 0.          3.66666667 -0.33333333]
 [ 0.          2.66666667  1.66666667]]
Após eliminação - Matriz A:
 [[ 3.         -2.         -2.        ]
 [ 0.          3.66666667 -0.33333333]
 [ 0.          0.          1.90909091]]
Pivô encontrado: 1.909090909090909
Após eliminação - Matriz A:
 [[ 3.         -2.         -2.        ]
 [ 0.          3.66666667 -0.33333333]
 [ 0.          0.          1.90909091]]
Solução encontrada: [ 1. -2.  4.]
[ 1. -2.  4.]
[ 1. -2.  4.]


### Decomposição LU

Um método alternativo à eliminação de gauss é a decomposição da matriz de $\textbf{A}$ em:

\
\begin{align}
\textbf{A} =\textbf{L}\,\textbf{U}
\end{align}

- $\textbf{L}$ é uma matriz triangular inferior (zeros em cima, valores em baixo);

- $\textbf{U}$ é uma matriz triangular superior (valores em cima, zeros em baixo).

Consideremos a matriz $\textbf{A}$:

\
\begin{align}
\textbf{A} =
\begin{bmatrix}
a_{1,1} & a_{1,2} & a_{1,3} & a_{1,4} \\
a_{2,1} & a_{2,2} & a_{2,3} & a_{2,4} \\
a_{3,1} & a_{3,2} & a_{3,3} & a_{3,4} \\
a_{4,1} & a_{4,2} & a_{4,3} & a_{4,4}
\end{bmatrix}
\end{align}

Agora iremos fazer as seguintes operações:

\
\begin{align}
L_1 = \frac{L_1}{a_{1,1}} - a_{1,1} L_1
\end{align}

\
\begin{array}{cc}
\frac{1}{a_{1,1}}\,
\begin{bmatrix}
1 & 0 & 0 & a_0 \\
-a_{2,1} & a_{1,1} & 0 & 0 \\
-a_{3,1} & a_{3,2} & a_{1,1} & 0 \\
-a_{4,1} & a_{4,2} & 0 & a_{1,1}
\end{bmatrix} & 
\begin{bmatrix}
a_{1,1} & a_{1,2} & a_{1,3} & a_{1,4} \\
a_{2,1} & a_{2,2} & a_{2,3} & a_{2,4} \\
a_{3,1} & a_{3,2} & a_{3,3} & a_{3,4} \\
a_{4,1} & a_{4,2} & a_{4,3} & a_{4,4}
\end{bmatrix}=
\begin{bmatrix}
1 & b_{1,2} & b_{1,3} & b_{1,4} \\
0 & b_{2,2} & b_{2,3} & b_{2,4} \\
0 & b_{3,2} & b_{3,3} & b_{3,4} \\
0 & b_{4,2} & b_{4,3} & b_{4,4}
\end{bmatrix}
\end{array}


Desta forma denominaremos a seguinte matriz triangular inferior:

\
\begin{array}{cc}
L_1 =
\frac{1}{a_{1,1}}\,
\begin{bmatrix}
1 & 0 & 0 & a_0 \\
-a_{2,1} & a_{1,1} & 0 & 0 \\
-a_{3,1} & a_{3,2} & a_{1,1} & 0 \\
-a_{4,1} & a_{4,2} & 0 & a_{1,1}
\end{bmatrix}
\end{array}

E agora voltamos a realizar o mesmo processo, dividindo todos os elementos da matriz resultante do última operação pelo segundo elemento da diagonal:

\
\begin{array}{cc}
\frac{1}{b_{2,2}}\,
\begin{bmatrix}
b_{2,2} & 0 & 0 & 0 \\
0 & 1 & 0 & 0 \\
0 & -b_{3,2} & b_{2,2} & 0 \\
0 & -b_{4,2} & 0 & b_{2,2}
\end{bmatrix} & 
\begin{bmatrix}
1 & b_{1,2} & b_{1,3} & b_{1,4} \\
0 & b_{2,2} & b_{2,3} & b_{2,4} \\
0 & b_{3,2} & b_{3,3} & b_{3,4} \\
0 & b_{4,2} & b_{4,3} & b_{4,4}
\end{bmatrix}=
\begin{bmatrix}
1 & c_{1,2} & c_{1,3} & c_{1,4} \\
0 & 1 & c_{2,3} & c_{2,4} \\
0 & 0 & c_{3,3} & c_{3,4} \\
0 & 0 & c_{4,3} & c_{4,4}
\end{bmatrix}
\end{array}

Logo, consideramos que $L_2$ é:

\
\begin{array}{cc}
L_1=\frac{1}{b_{2,2}}\,
\begin{bmatrix}
b_{2,2} & 0 & 0 & 0 \\
0 & 1 & 0 & 0 \\
0 & -b_{3,2} & b_{2,2} & 0 \\
0 & -b_{4,2} & 0 & b_{2,2}
\end{bmatrix}
\end{array}

E com isto temos ainda:

\
\begin{array}{cc}
L_3=\frac{1}{c_{3,3}}\,
\begin{bmatrix}
c_{3,3} & 0 & 0 & 0 \\
0 & c_{3,3} & 0 & 0 \\
0 & 0 & 1 & 0 \\
0 & 0 & -c_{4,3} & c_{3,3}
\end{bmatrix}
\end{array}

\
\begin{array}{cc}
L_4=\frac{1}{d_{4,4}}\,
\begin{bmatrix}
d_{4,4} & 0 & 0 & 0 \\
0 & d_{4,4} & 0 & 0 \\
0 & 0 & d_{4,4} & 0 \\
0 & 0 & 0 & 1 
\end{bmatrix}
\end{array}

Daqui tiramos que: $L_4\,L_3\,L_2\,L_1\,A\,x=L_4\,L_3\,L_2\,L_1\,v$

\
E que $L = L_{4}^{-1}\,L_{3}^{-1}\,L_{2}^{-1}\,L_{1}^{-1}$ e $U = L_4\,L_3\,L_2\,L_1\,A$

\
Logo como $L\,U = A \implies L\,U\,x = v$ 

Mas como é que calculamos os elementos de L e U de forma efetiva? Chegamos à seguinte conclusão:

\
\begin{align}
L_{i,j} &= A_{i,j} - \sum_{k=1}^{i-1} L_{i,k}\, U_{k,j}\\ U_{i,j} &= \frac{1}{L_{i,i}}(A_{i,j} - \sum_{k=1}^{j-1} L_{i,k}\, U_{k,j})
\end{align}


In [88]:
#Código para decomposição A em LU sem pivotamento

A=np.array([[1,2,1],[3,-2,-2],[1,3,-1]],float)
v=np.array([1,-1,-9],float)


def lu_decomposition(A):
    N = len(A)
    L = np.zeros((N, N))
    U = np.zeros((N, N))

    for j in range(N):
        L[j][j] = 1.0

        for i in range(j + 1):
            U[i][j] = A[i][j] - sum(U[k][j] * L[i][k] for k in range(i))
        
        for i in range(j, N):
            L[i][j] = (A[i][j] - sum(U[k][j] * L[i][k] for k in range(j))) / U[j][j]
    
    return L, U

L,U = lu_decomposition(A)
print(np.dot(L,U))
print(lu_decomposition(A))


A=np.array([[1,2,1],[3,-2,-2],[1,3,-1]],float)
v=np.array([1,-1,-9],float)

P,L,U = scipy.linalg.lu(A)
print(np.dot(L,U))
print(scipy.linalg.lu(A))

[[8. 5. 6. 6.]
 [5. 4. 7. 9.]
 [1. 9. 7. 9.]
 [7. 2. 6. 9.]]
5.25
[[8. 5. 6. 6.]
 [1. 9. 7. 9.]
 [5. 4. 7. 9.]
 [7. 2. 6. 9.]]
[[ 1.          0.          0.          0.        ]
 [ 0.125       1.          0.          0.        ]
 [ 0.625       0.10447761  1.          0.        ]
 [ 0.875      -0.28358209  0.97126437  1.        ]]
8.25


In [51]:
#Código de decomposição de A com LU e pivotamento parcial 

A=np.array([[1,2,1],[3,-2,-2],[1,3,-1]],float)

def lu_decomposition_pivparcial(A):
    N = len(A)
    L = np.zeros((N, N))
    U = np.zeros((N, N))

    for j in range(N):
        # Pivotamento parcial
        max_index = max(range(j, N), key=lambda i: abs(A[i, j]))
        A[[j, max_index]] = A[[max_index, j]]

        L[j][j] = 1.0
        for i in range(j + 1):
            U[i][j] = A[i][j] - sum(U[k][j] * L[i][k] for k in range(i))
        
        for i in range(j, N):
            L[i][j] = (A[i][j] - sum(U[k][j] * L[i][k] for k in range(j))) / U[j][j]

        print("\nTroca da linha ",j,"pelal linha do pivo ",max_index, "\nMatriz L:",L, "\nMatriz U:", U)
        
    return L, U

L,U = lu_decomposition_pivparcial(A)
print(np.dot(L,U))
print(lu_decomposition_pivparcial(A))

def lu_decomposition_pivpartial(A):
    N = len(A)
    L = np.eye(N)
    U = np.copy(A)

    for j in range(N):
        pivot_row = np.argmax(abs(U[j:, j])) + j
        if pivot_row != j:
            U[[j, pivot_row]] = U[[pivot_row, j]]
            L[[j, pivot_row], :j] = L[[pivot_row, j], :j]

        L[j, j] = 1.0
        for i in range(j + 1):
            U[i, j] = A[i, j] - np.dot(L[i, :i], U[:i, j])
        
        for i in range(j, N):
            L[i, j] = (A[i, j] - np.dot(L[i, :j], U[:j, j])) / U[j, j]
        print("\nPivo de troca:", pivot_row,"\nMatriz L:",L, "\nMatriz U:", U)
    return L, U

A=np.array([[1,2,1],[3,-2,-2],[1,3,-1]],float)
L,U = lu_decomposition_pivpartial(A)
print(np.dot(L,U))
print(lu_decomposition_pivpartial(A))



Troca da linha  0 pelal linha do pivo  1 
Matriz L: [[1.         0.         0.        ]
 [0.33333333 0.         0.        ]
 [0.33333333 0.         0.        ]] 
Matriz U: [[3. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Troca da linha  1 pelal linha do pivo  2 
Matriz L: [[1.         0.         0.        ]
 [0.33333333 1.         0.        ]
 [0.33333333 0.72727273 0.        ]] 
Matriz U: [[ 3.         -2.          0.        ]
 [ 0.          3.66666667  0.        ]
 [ 0.          0.          0.        ]]

Troca da linha  2 pelal linha do pivo  2 
Matriz L: [[1.         0.         0.        ]
 [0.33333333 1.         0.        ]
 [0.33333333 0.72727273 1.        ]] 
Matriz U: [[ 3.         -2.         -2.        ]
 [ 0.          3.66666667 -0.33333333]
 [ 0.          0.          1.90909091]]
[[ 3. -2. -2.]
 [ 1.  3. -1.]
 [ 1.  2.  1.]]

Troca da linha  0 pelal linha do pivo  0 
Matriz L: [[1.         0.         0.        ]
 [0.33333333 0.         0.        ]
 [0.33333333 0.         0.        ]] 

## Resolução do sistema final

Temos agora que $A = L\,U$, ou seja:

\
\begin{array}{cc}
\begin{bmatrix}
a_{1,1} & a_{1,2} & a_{1,3} & a_{1,4} \\
a_{2,1} & a_{2,2} & a_{2,3} & a_{2,4} \\
a_{3,1} & a_{3,2} & a_{3,3} & a_{3,4} \\
a_{4,1} & a_{4,2} & a_{4,3} & a_{4,4}
\end{bmatrix} =
\begin{bmatrix}
l_{1,1} & 0 & 0 & 0 \\
l_{2,1} & l_{2,2} & 0 & 0 \\
l_{3,1} & l_{3,2} & l_{3,3} & 0 \\
l_{4,1} & l_{4,2} & l_{4,3} & l_{4,4}
\end{bmatrix} &
\begin{bmatrix}
u_{1,1} & u_{1,2} & u_{1,3} & u_{1,4} \\
0 & u_{2,2} & u_{2,3} & u_{2,4} \\
0 & 0 & u_{3,3} & u_{3,4} \\
0 & 0 & 0 & u_{4,4}
\end{bmatrix}
\end{array}

\
\begin{array}{cc}
\begin{bmatrix}
l_{1,1} & 0 & 0 & 0 \\
l_{2,1} & l_{2,2} & 0 & 0 \\
l_{3,1} & l_{3,2} & l_{3,3} & 0 \\
l_{4,1} & l_{4,2} & l_{4,3} & l_{4,4}
\end{bmatrix} &
\begin{bmatrix}
u_{1,1} & u_{1,2} & u_{1,3} & u_{1,4} \\
0 & u_{2,2} & u_{2,3} & u_{2,4} \\
0 & 0 & u_{3,3} & u_{3,4} \\
0 & 0 & 0 & u_{4,4}
\end{bmatrix} &
\begin{bmatrix}
x_1 \\
x_2 \\
x_3 \\
x_4
\end{bmatrix} =
\begin{bmatrix}
v_1 \\
v_2 \\
v_3 \\
v_4
\end{bmatrix}
\end{array}





In [92]:
#Código para decomposição de A em LU com resolução do sistema de eqs lineares


def Resolve_LU(A,v):
    N = len(A)
    L = np.zeros((N, N))
    U = np.zeros((N, N))
    
    for j in range(N):
        L[j][j] = 1.0

        for i in range(j + 1):
            U[i][j] = A[i][j] - sum(U[k][j] * L[i][k] for k in range(i))
        
        for i in range(j, N):
            L[i][j] = (A[i][j] - sum(U[k][j] * L[i][k] for k in range(j))) / U[j][j]
    
    return L,U

def matrix_tridiagonal(n):
    # Elementos da diagonal principal
    diag_principal = np.array([5.0, 2.0, 2.0, 1.0, 5.0, 1.0, 5.0, 7.0, 8.0, 9.0])
    
    # Elementos da subdiagonal inferior
    subdiagonal_inferior = np.full(n - 1, 1.0)
    
    # Elementos da subdiagonal superior
    subdiagonal_superior = np.full(n - 1, 2.0)
    
    # Construindo a matriz utilizando a função np.diag para a diagonal principal e np.diagflat para as subdiagonais
    A = np.diag(diag_principal) + np.diagflat(subdiagonal_inferior, -1) + np.diagflat(subdiagonal_superior, 1)
    
    return A

n = 10
A=matrix_tridiagonal(n)
print("Matriz A:")
print(A)

L,U= Resolve_LU(A,v)
print(L[5,5])
P,L,U = scipy.linalg.lu(A)
print(L[5,5])

Matriz A:
[[5. 2. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 2. 2. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 2. 2. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 2. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 5. 2. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 2. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 5. 2. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 7. 2. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 8. 2.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 9.]]
1.0
1.0


### Decomposição de A em Q R

In [81]:
#Código para decomposição de A em QR

A=np.array([[1,2,1],[3,-2,-2],[1,3,-1]],float)
v=np.array([1,-1,-9],float)


def decomp_qr(A):
    N = len(A)
    Q = np.zeros_like(A, dtype=float)
    R = np.zeros_like(A, dtype=float)
    
    u_ant = A[:, 0]
    q_ant = u_ant / np.linalg.norm(u_ant)
    Q[:, 0] = q_ant
    
    R[0, 0] = np.linalg.norm(u_ant)
    
    for j in range(1, N):
        ui = A[:, j] - np.sum(np.dot(Q[:, i], A[:, j]) * Q[:, i] for i in range(j))
        qi = ui / np.linalg.norm(ui)
        R[j, j] = np.linalg.norm(ui)
        for i in range(j,N):
            R[j-1,i] = np.dot(Q[: ,j-1], A[:,i])
        Q[:, j] = qi
    
    return Q, R

A=np.array([[9, 4, 6, 8, 3, 8], [6, 7, 9, 6, 9, 6], [1, 4, 0, 2, 2, 5], [2, 2, 3, 7, 1, 4],[5, 7, 0, 8, 2, 2], [1, 4, 4, 7, 7, 2]],float)
v=np.array([1,-1,-9],float)
Q,R = decomp_qr(A)
print("\n \n", Q[4,5], "\n \n", R)
print("\n \n", np.dot(Q,R))

A=np.array([[9, 4, 6, 8, 3, 8], [6, 7, 9, 6, 9, 6], [1, 4, 0, 2, 2, 5], [2, 2, 3, 7, 1, 4],[5, 7, 0, 8, 2, 2], [1, 4, 4, 7, 7, 2]],float)
v=np.array([1,-1,-9],float)

Q,R=np.linalg.qr(A)
a=np.linalg.norm([1,2,1])
print("\n \n", np.multiply(1/a,[1,2,1]))
print(np.dot(Q,R))
print("\n \n", Q ,"\n \n", R)
print(Q[4,5])


 
 -0.4353914284083083 
 
 [[12.16552506 10.27493671  9.69954025 14.05611341  8.38434835 10.93253266]
 [ 0.          6.66525886  1.40097152  5.33727573  6.12899697  1.75070754]
 [ 0.          0.          6.77910007  1.05984435  5.9136353   1.99241314]
 [ 0.          0.          0.          6.23024024 -0.45440158  0.46152706]
 [ 0.          0.          0.          0.          2.22722598 -1.78020975]
 [ 0.          0.          0.          0.          0.          4.36610682]]

 
 [[9. 4. 6. 8. 3. 8.]
 [6. 7. 9. 6. 9. 6.]
 [1. 4. 0. 2. 2. 5.]
 [2. 2. 3. 7. 1. 4.]
 [5. 7. 0. 8. 2. 2.]
 [1. 4. 4. 7. 7. 2.]]

 
 [0.40824829 0.81649658 0.40824829]
[[9. 4. 6. 8. 3. 8.]
 [6. 7. 9. 6. 9. 6.]
 [1. 4. 0. 2. 2. 5.]
 [2. 2. 3. 7. 1. 4.]
 [5. 7. 0. 8. 2. 2.]
 [1. 4. 4. 7. 7. 2.]]

 
 [[-0.73979544  0.5403168  -0.06176443 -0.08838051 -0.23091948  0.30953302]
 [-0.49319696 -0.28992609  0.56202711  0.49364215  0.2065468  -0.26548258]
 [-0.08219949 -0.47341078 -0.21544634  0.23334408  0.18978014  0.79513

C:\Users\manud\AppData\Local\Temp\ipykernel_9588\2057968338.py:19: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  ui = A[:, j] - np.sum(np.dot(Q[:, i], A[:, j]) * Q[:, i] for i in range(j))


## Resolução de equações não lineares

### Método de relaxação
Peguemos na seguinte equação: $x = 2 - e^{-x} \iff x + e^{-x} = 2$
Se soubermos em que intervalo podemos encontrar a solução, então podemos determinar o resultado, por meio de iterações sucessivas. Por exemplo, peguemos no valor $x=1$:

\
$$
\begin{align}
x' = 2 - e^{-1} \approx 1,632 \implies x'' = 2 - e^{-1,632} \approx 1,804 \implies (...)
\end{align}
$$

##### Problemas deste método:
 - Nem sempre temos uma equação: $x = f(x)$; Exemplo: $\log{x} + x^2 - 1 = 0$ .
 - A equação poderá ter mais que 1 solução, não convergindo para um único valor.
 - Às vezes, a forma como etsá disposta a equação matemática poderá influenciar a convergência para a soluçãpo pretendida. Exemplo: $x = e^{1-x^2} \to$ não existe convergência para a solução que é $x=1$; já com um rearranjo da equação $ x = \sqrt{1 - \log x}$ já obtemos a solução esperada.
 
##### Teoria por trás do rearranjo de equações

Supondo que temos $f(x) = x$ e que a solução é $x = x^*$, façamos uma expansão em série de Taylor, ao valor $x'$, obtido a partir da 1ª iteração com o valor $x$:
$$
\begin{align}
x' = f(x) = f(x^*) +f'(x^*)(x-x^*) + O(x^3)
\end{align}
$$

\
Por definição $x^*$ é a solução da equação, ou seja, $f(x^*) = x^*$ :

$$
x' - x^* = f'(x^*)(x-x^*)
$$

Note-se que a distância entre o nosso $x$ "atual" e anossa solução, $(x - x^*)$ é multilpliado por um fator, $C = f'(x^*)$, logo o nosso x' só se aproximará ou convergirá para a nossa solução, se e apenas se, $C =|f'(x^*)| < 1$.

###### E se $C = |f'(x^*)|>1$ o que fazemos?
Neste caso, rearranjamos a equação, invertendo a função tal que, $x = f^{-1}(x)$. Agora calculamos a derivada:
$$
u = f^{-1}(x) \to x = f(u) \implies \frac{dx}{du} = f'(u)
$$

\
Quando $x = x^* \implies u = f^{-1}(x^*) = x^*$ , logo:
$$
\frac{du}{dx} = \frac 1 {f'(x^*)} \implies C = \frac 1{f'(x^*)} < 1
$$

#### Taxa de convergência
Vamos definir o erro em relação à iteração "atual" como $\epsilon = x^* - x$ e ao erro associado à iteração seguinte $\epsilon' = x^*- x'$, logo:
$$
\epsilon' = \epsilon f'(x^*) \implies x^* = x + \epsilon = x + \frac{\epsilon'}{f'(x^*)}
$$

\
Nisto obtemos: $\epsilon' = \frac{x-x'}{1-1/f'(x^*)} \approx \frac{x-x'}{1-1/f'(x)}$ , considerando que $x$ está muito próximo de $x^* \implies f'(x) = f'(x^*)$


### Método de relaxação para 2 ou + variáveis

#### Algoritmo de Jacobi
- Recorre ao método de relaxação.

In [20]:
#Algoritmo de Jacobi

def jacobi(A, v, eps, x0):
    N = len(A)
    C_inv = np.linalg.inv(A*np.eye(N))
    B = np.eye(N) - C_inv@A
    d=C_inv@v
    x_old = np.copy(x0)
    count = 0
    erro = 1
    while (erro >= eps):
        x = B@x_old + d
        erro = np.max(np.abs(x - x_old))/np.max(np.abs(x))
        x_old = np.copy(x)
        count+=1
    return x

x0 = np.zeros(N)
A = [[10,2,1], [1,5,1],[2,3,10]]
v = [7,-8,6]
print(jacobi(A,v,1e-6,x0))


[ 1.00000027 -1.99999965  1.00000039]


#### Algoritmo de Gauss-Seided
- Recorre ao método de relaxação.

In [5]:
# Algoritmo de Gauss-Seided

def gauss_seided(A,b, eps,x0):
    N = len(A)
    C_inv = np.linalg.inv(A*np.eye(N))
    B = np.eye(N) - C_inv@A
    d=C_inv@v
    x_old = np.copy(x0)
    erro = 1
    x=np.zeros(N)
    while (erro >= eps):
        for i in range(N):
            x[i] = B[i,0:]@x + d[i]
        erro = np.max(np.abs(x - x_old))/np.max(np.abs(x))
        x_old = np.copy(x)
    return x


A = [[10,2,1], [1,5,1],[2,3,10]]
v = [7,-8,6]
N = len(A)
x0 = np.zeros(N)
print(gauss_seided(A,v,1e-6,x0))
print(np.linalg.solve(A,v))

[ 0.99999999 -1.99999999  1.        ]
[ 1. -2.  1.]


### Método da bisseção

In [78]:
#Código para o método da bisseção

def f(x):
    return 2*np.sqrt(x)-2*np.tanh(x)-2

def bissecao(a, b, f, eps):
    if f(a) * f(b) >= 0:
        raise ValueError("A função não muda de sinal nos pontos a e b")

    x_1 = a
    x_2 = b
    x_linha = 0.5 * (x_1 + x_2)
    erro = abs(x_2 - x_1)
    while erro > eps:
        x_linha = 0.5 * (x_1 + x_2)
        if f(x_linha) * f(x_1) < 0:
            x_2 = x_linha
        else:
            x_1 = x_linha
        erro = abs(x_2 - x_1)
    return x_linha

print(bissecao(1, 10, f, 0.002197))

3.9981689453125


#### Método de Newton-Raphson

In [46]:

def f(x):
    return x**2 - 4

def f_deriv(x):
    return 2*x

def newton_raphson(x, f, f_deriv, eps):
    erro = 1
    x_linha = x - f(x)/f_deriv(x)
    while erro > eps:
        erro = abs(x-x_linha)
        x=x_linha
        x_linha = x - f(x)/f_deriv(x)
    return x_linha

print(newton_raphson(-5, f, f_deriv, 1e-6))

-2.0


In [2]:
def F(x):
    N = len(x)
    b = np.zeros(N)
    b[0] = x[0]**2 + x[1]**2 - 2
    b[1] = x[0]**2 - (x[1]**2)/9 - 1
    return b

def Jacobiano(x):
    N = len(x)
    A = np.zeros((N,N))
    A[0][0] = 2*x[0]
    A[0][1] = 2*x[1]
    A[1][0] = 2*x[0]
    A[1][1] = -(2/9)*x[1]
    return A

x0 = [1,1]
A = Jacobiano(x0)
A = np.array(A)
b = F(x0)
b = np.array(b)
s = np.linalg.solve(A,-b)
print(s)
print(F([0.05, -0.05]))

[ 0.05 -0.05]
[-1.995      -0.99777778]


In [3]:
def gauss_jordan_inverse(A):
    n = len(A)
    A_inv = np.zeros((n, n))
    A_ext = np.hstack((A, np.identity(n)))
    
    pivots = []

    for i in range(n):
        # Pivoteamento parcial
        pivot_row = max(range(i, n), key=lambda j: abs(A_ext[j, i]))
        pivots.append(pivot_row)
        A_ext[[i, pivot_row]] = A_ext[[pivot_row, i]]

        # Normalizando o pivô
        pivot = A_ext[i, i]
        A_ext[i] /= pivot

        # Eliminação gaussiana
        for j in range(n):
            if i != j:
                factor = A_ext[j, i]
                A_ext[j] -= factor * A_ext[i]

    # Extraindo a matriz inversa
    A_inv = A_ext[:, n:]

    return A_inv, pivots

# Testando a função
A = np.array([[2, 1, 1], [1, -1, 0], [3, -1, 2]])
A_inv, pivots = gauss_jordan_inverse(A)

print("Índices dos pivôs:")
print(pivots)
print("\nInversa de A:")
print(A_inv)

# Verificando a inversa: A * A_inv deve ser uma matriz identidade
identity = np.dot(A, A_inv)
print("\nVerificação da inversa (A * A_inv):")
print(identity)

Índices dos pivôs:
[2, 2, 2]

Inversa de A:
[[ 0.5   0.75 -0.25]
 [ 0.5  -0.25 -0.25]
 [-0.5  -1.25  0.75]]

Verificação da inversa (A * A_inv):
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.11022302e-16  1.00000000e+00 -1.11022302e-16]
 [-3.33066907e-16  0.00000000e+00  1.00000000e+00]]


#### Método da secante

In [ ]:
#método da secante
def f(x):
    return 0

def método_secante(x0,x1,erro):
    e=erro+1
    while e>erro:
        x2=x1-f(x1)*(x1-x0)/(f(x1)-f(x0))
        e=x2-x1
        x0=x1
        x1=x2
    return x2

### Método da secção aurea / dos máximos e mínimos

In [76]:
def f(x):
    return x**2 - 4

#está feita para encontrar um mínimo se quiser determinar um máximo fazer -f(x)
def metodo_sec_aurea(x1,x4,erro):
    z=(1+np.sqrt(5))/2
    x2=x4-(1/z)*(x4-x1)
    x3=x1+(1/z)*(x4-x1)
    e=erro+1
    while erro<e:
        if f(x2)<f(x3):
            x4=x3
            x3=x2
            x2=x4-(1/z)*(x4-x1)
        else:
            x1=x2
            x2=x3
            x3=x1+(1/z)*(x4-x1)
        e=x4-x1
    return (x2+x3)/2

x=metodo_sec_aurea(1,3,1e-6)
print(x)
print(f(x))

1.0000003321873976
-2.9999993356250947


### Método de Gauss-Newton

In [77]:
#método de Gauss_Newton

def P(x):
    return x**2 - 4
h=0.01

def derivada_P(x,h):
    return (P(x+h/2)-P(x-h/2))/h

def segunda_derivada_P(x,h):
    return  (P(x+h)-2*P(x)+P(x-h))/h**2

def método_Gauss_Newton(x0,erro):
    e=erro+1
    while erro<e:
        x=x0-derivada_P(x0,h)/segunda_derivada_P(x0,h)
        e=x-x0
        x0=x
    return x0

print(método_Gauss_Newton(1,1e-6))
print(f(2e-12))

2.1316282072803006e-12
-4.0


In [73]:
def f(x):
    return x**2 - 4

# Derivada da função de exemplo
def df(x):
    return 2 * x

# Método do gradiente (Gauss-Newton)
def gauss_newton(x0, learning_rate, tolerance):
    x = x0
    while True:
        grad = df(x)
        x_new = x - learning_rate * grad
        
        # Verifica a convergência
        if np.abs(f(x_new) - f(x)) < tolerance:
            break
        
        x = x_new
    
    return x

# Exemplo de uso
x0 = 2.0  # Valor inicial
learning_rate = 0.1  # Taxa de aprendizado
tolerance = 1e-6  # Tolerância para a convergência

min_x = gauss_newton(x0, learning_rate, tolerance)
print("Mínimo local encontrado:", min_x)
print("Valor da função no mínimo local:", f(min_x))

Mínimo local encontrado: 0.0015845632502852873
Valor da função no mínimo local: -3.999997489159306


### Matrizes banda

In [102]:

def matrix_tridiagonal(n):
    # Elementos da diagonal principal
    diag_principal = np.ones(n)
    
    # Elementos da subdiagonal inferior
    subdiagonal_inferior = np.full(n - 1, 1.0)
    
    # Elementos da subdiagonal superior
    subdiagonal_superior = np.full(n - 1, 1.0)
    
    # Construindo a matriz utilizando a função np.diag para a diagonal principal e np.diagflat para as subdiagonais
    A = np.diag(diag_principal) + np.diagflat(subdiagonal_inferior, -1) + np.diagflat(subdiagonal_superior, 1)
    
    return A

n = 10
A = matrix_tridiagonal(n)
print("Matriz A:")
print(A)

# Calculando o produto da matriz tridiagonal A pela matriz identidade I
I = np.eye(n)
result = np.dot(A, I)
print("\nProduto de A por I:")
print(result)

Matriz A:
[[1. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]]

Produto de A por I:
[[1. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]]


In [ ]:
A=np.array([1,1,0,0],[1,1,0,0],[0,1])